### ISSUE TITLE
Show machines nested in a state on hover / click

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jfabry/LiveRobotProgramming#29]
```
Machines that are nested in a given state should be shown on mouse hover or 
click, ideally with updating of the active state et al.
```

Original issue reported on code.google.com by `jfa...@gmail.com` on 6 Aug 2014 at 7:11

**Comment by mcamp** [comment]
We should support some kind of visualization to tell to developers what states has nested machines and which machine is nested. It does not need to be the complete machine, just an indication that the state has something inside. I change the priority to high because we are far behind of SMACH without some kind of indication.

**Comment by jfabry** [comment]
Fixed in LiveRobotics-UI-johanfabry.144 Added indication of nested machine in the state circle
